### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by vaisanem** [Corned/Blabber#1]
Koodia katseltu 1.4.2017 klo 22.34 lähtien.

Varhaista sanoa vielä mitään hirveän edistyksellistä, vaikka oletkin muokkaus-toiminnoilla päässyt jo aikataulua edellekin. Koodi on siistiä ja toimii, joka on todettu käytännössä. 

Blab-tietokantataulussa näytti olevan eräs attribuutti deleted. Onkohan poistettaessa ajateltu muuttaa vain sen arvoa, rivin kokonaan poistamisen sijaan?

Paljon hyviä ominaisuuksia suunniteltuna. Vaikka arvosteluperusteet vaativat, niin viestien muokkaus myöhemmin voisi käytännössä olla ikävää, jos sitä on esimerkiksi uudelleenjaettu. Jos kaiken lisäksi kuitenkin sattuu ylimääräistä aikaa, niin global feediin haku- tai suodatustoiminto voisi olla hyvä plussa.

**Comment by Corned** [comment]
Kiitos palautteesta.

Juoni deleted-attribuutin takana on se, jos käyttäjä (tai vaikkapa pääkäyttäjä) haluaa päästä käsiksi poistettuihin Blabbeihin. Tämä mahdollistaisi blabbien palautuksen ja ylläpitö pääsisi käsiksi poistettuihin blabbeihin.

Blabin muokkaus on ongelmallinen pulma. Tämän uudelleenjako-muokkaus-ongelman voisi korjata sallimalla editoinnit vain minuutin sisällä blabin lähettämisestä. 

Kiitos vielä kerran kattavasta palautteesta.
