### ISSUE TITLE
Koodikatselmointi 2

### ISSUE THREAD

**Issue by MJL7068** [Corned/Blabber#2]
Latasin koodin ja aloitin katselmoinnin perjantaina 21.4 klo 9.

Kokonaisuudessaan ohjelma vaikuttaa toimivalta ja hyvin tehdyltä ja se täyttää dokumentaatiossa esitetyt vaatimukset.

Dokumentaatio oli hyvin tehty ja selkeytti ohjelman toimintaa. Kappaleessa järjestelmän yleisrakenne olisi voinut kirjoittaa vähän siitä miten järjestelmä käyttää istuntoa ja miten se vaikuttaa ohjelman toimintaan.

Lähdekoodi oli selkeää ja hyvin järjesteltyä. Funktioihin liitetyt kommentit olivat selkeitä, vaikka suurimmassa osassa funktion toiminta oli jo ilmankin kommentteja hyvin ymmärrettävissä.

Sisään ja uloskirjautuminen näytti toimivan hyvin. Järjestelmä estää pääsyn niille sivuille joille kirjautumattoman ei pitäisikään päästä.

Testatessani ohjelmaa huomasin pieniä virheitä, jotka olisi syytä korjata ennen lopullista palautusta:

Jos editoin viestiä ja jätän viestikentän tyhjäksi, ohjelma kaatuu sen sijaan että se palautuisi lomakkeeseen. Tämä johtuu ilmeisesti siitä että luokan blabcontroller.php funktiossa update() on käytetty sekä $errs- että $errors-muuttujaa (riveillä 114 ja 120) jolloin ohjelma ei löydä $errors-muuttujaa, koska sitä ei ole aiemmin määritelty.

Jos menen käyttäjän suosikkiblabien sivuille ja yritän painaa jonkin blabin kohdalla EXPAND-painiketta, se johtaa ohjelman kaatumiseen. Tämä johtuu ilmeisesti siitä että favourites.html-näkymässä EXPAND-painikkeen linkki on muotoa /blab/show/:id vaikka sen pitäisi olla muotoa blab/:id.

Jos haen osoitetta, jossa blabin id:ksi on määritelty jokin merkkijono, esimerkiksi http://koliver.users.cs.helsinki.fi/blabber/blab/qwe, johtaa tämä ohjelman kaatumiseen. Katsomalla koodia huomaan että haettavasta id:stä tarkistetaan fiksusti että se ei ole pienempi kuin 0 tai isompi kuin 2147483647, mutta siinä ei tarkisteta, onko haettava id oikeasti numeromuodossa.

Ohjelmaa voisi myöhemmin laajentaa esimerkiksi käyttäjän mahdollisuudella lisätä itselleen profiilikuva tai lisätä julkaistaviin viesteihin kuvia. Lisäksi käyttäjä voisi seurata muita käyttäjiä, jolloin heidän viestinsä ilmestyisivät käyttäjän henkilökohtaiseen feediin. Nämä ominaisuudet ovat kuitenkin todennäköisesti jo tämän projektin ulkopuolella. Jos aikaa jää, voisi käyttäjän hakeminen käyttäjänimen perusteella olla melko helppo toteuttaa materiaalin vinkkien avulla.

**Comment by Corned** [comment]
Kiitos palautteesta, virheet ovat jo korjattu.

Käyttäjien seuraaminen ja hakufunktio ovat työn alla.
